In [2]:
import numpy as np
import pandas as pd
scores = np.random.randint(20,100,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns = ['國文','英文','數學','地理','歷史'],
             index = range(1,51))

sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values
scores_df

    國文  英文  數學  地理  歷史   總分    平均
1   76  58  44  35  44  257  51.4
2   53  49  70  56  91  319  63.8
3   27  79  49  99  93  347  69.4
4   38  75  96  59  63  331  66.2
5   52  43  65  77  74  311  62.2
6   46  22  21  87  48  224  44.8
7   77  35  59  31  30  232  46.4
8   30  36  79  53  95  293  58.6
9   41  68  73  59  42  283  56.6
10  57  46  61  43  83  290  58.0
11  31  38  25  87  36  217  43.4
12  87  25  74  86  40  312  62.4
13  56  49  96  83  56  340  68.0
14  33  22  49  92  74  270  54.0
15  44  80  33  78  47  282  56.4
16  77  66  57  29  46  275  55.0
17  42  49  57  94  28  270  54.0
18  88  44  66  83  74  355  71.0
19  46  77  40  47  27  237  47.4
20  25  63  98  87  48  321  64.2
21  53  28  89  33  48  251  50.2
22  75  22  62  86  53  298  59.6
23  96  53  39  57  77  322  64.4
24  52  70  79  97  75  373  74.6
25  69  49  54  79  55  306  61.2
26  78  86  54  36  57  311  62.2
27  40  88  30  48  79  285  57.0
28  69  58  71  91  62  351  70.2
29  71  38  96  32  78  315  63.0
30  87  36  64  44  79  310  62.0
31  47  77  55  36  68  283  56.6
32  51  73  60  97  89  370  74.0
33  42  57  78  76  93  346  69.2
34  29  55  30  73  32  219  43.8
35  50  89  77  38  89  343  68.6
36  67  73  76  34  56  306  61.2
37  81  85  29  24  64  283  56.6
38  88  28  94  65  41  316  63.2
39  55  68  21  86  42  272  54.4
40  92  48  21  55  44  260  52.0
41  27  26  59  71  98  281  56.2
42  33  88  60  49  30  260  52.0
43  63  66  74  50  64  317  63.4
44  27  71  77  58  72  305  61.0
45  24  58  77  98  40  297  59.4
46  25  73  49  77  22  246  49.2
47  40  26  75  23  88  252  50.4
48  21  84  90  29  23  247  49.4
49  32  62  94  27  95  310  62.0
50  25  23  46  51  33  178  35.6

In [11]:
scores_df
pdstyle = scores_df.style\
    .format(precision=2)\
    .highlight_between(left=50,right=59,props='color:white ; background-color:#CB1B45;')\
    .highlight_max(axis=1,subset=scores_df.columns[:5], props='color:white ; background-color:#2B5F75;')\
    #.to_excel('styleExcel.xlsx',sheet_name='3年1班')

In [12]:
from openpyxl import load_workbook
#book = load.workbook('天龍國小.xlsx')
writer = pd.ExcelWriter('天龍國小.xlsx', engine='openpyxl')
#writer.book = book
pdstyle.to_excel(writer, sheet_name="3年2班")