In [1]:
import numpy as np
import pandas as pd
scores = np.random.randint(20,100,size=(50,5))
scores_df = pd.DataFrame(scores,
             columns = ['國文','英文','數學','地理','歷史'],
             index = range(1,51))
display(scores_df)

sum_values = scores_df.sum(axis=1)
mean_values = scores_df.mean(axis=1)
scores_df['總分'] = sum_values
scores_df['平均'] = mean_values
scores_df

    國文  英文  數學  地理  歷史
1   77  47  80  78  32
2   32  84  40  24  85
3   54  30  23  74  67
4   49  95  98  85  39
5   89  64  80  30  37
6   25  37  48  88  80
7   62  87  91  31  81
8   44  48  23  66  57
9   51  64  73  45  84
10  65  92  42  78  85
11  41  97  79  36  88
12  53  38  79  33  60
13  45  31  32  22  39
14  85  94  46  31  43
15  76  44  83  72  78
16  20  66  59  75  76
17  47  48  31  73  78
18  45  69  83  36  44
19  22  25  72  36  77
20  33  81  25  67  57
21  22  76  83  81  75
22  92  31  84  46  64
23  35  95  60  42  57
24  45  87  34  81  96
25  98  72  52  85  60
26  92  25  70  46  49
27  26  44  58  85  91
28  33  40  22  36  97
29  96  88  33  49  98
30  41  74  21  72  75
31  43  70  60  62  65
32  62  26  60  43  33
33  86  90  38  25  77
34  31  70  94  29  52
35  62  22  33  32  82
36  29  54  29  29  87
37  84  51  22  70  99
38  58  49  27  58  79
39  24  56  88  62  98
40  70  61  91  55  81
41  43  45  36  84  81
42  84  73  69  95  41
43  71  64  61  97  34
44  57  71  42  93  97
45  75  78  56  25  88
46  63  78  80  64  96
47  25  61  99  60  40
48  83  46  38  31  92
49  70  32  53  64  62
50  31  39  95  57  77

    國文  英文  數學  地理  歷史   總分    平均
1   77  47  80  78  32  314  62.8
2   32  84  40  24  85  265  53.0
3   54  30  23  74  67  248  49.6
4   49  95  98  85  39  366  73.2
5   89  64  80  30  37  300  60.0
6   25  37  48  88  80  278  55.6
7   62  87  91  31  81  352  70.4
8   44  48  23  66  57  238  47.6
9   51  64  73  45  84  317  63.4
10  65  92  42  78  85  362  72.4
11  41  97  79  36  88  341  68.2
12  53  38  79  33  60  263  52.6
13  45  31  32  22  39  169  33.8
14  85  94  46  31  43  299  59.8
15  76  44  83  72  78  353  70.6
16  20  66  59  75  76  296  59.2
17  47  48  31  73  78  277  55.4
18  45  69  83  36  44  277  55.4
19  22  25  72  36  77  232  46.4
20  33  81  25  67  57  263  52.6
21  22  76  83  81  75  337  67.4
22  92  31  84  46  64  317  63.4
23  35  95  60  42  57  289  57.8
24  45  87  34  81  96  343  68.6
25  98  72  52  85  60  367  73.4
26  92  25  70  46  49  282  56.4
27  26  44  58  85  91  304  60.8
28  33  40  22  36  97  228  45.6
29  96  88  33  49  98  364  72.8
30  41  74  21  72  75  283  56.6
31  43  70  60  62  65  300  60.0
32  62  26  60  43  33  224  44.8
33  86  90  38  25  77  316  63.2
34  31  70  94  29  52  276  55.2
35  62  22  33  32  82  231  46.2
36  29  54  29  29  87  228  45.6
37  84  51  22  70  99  326  65.2
38  58  49  27  58  79  271  54.2
39  24  56  88  62  98  328  65.6
40  70  61  91  55  81  358  71.6
41  43  45  36  84  81  289  57.8
42  84  73  69  95  41  362  72.4
43  71  64  61  97  34  327  65.4
44  57  71  42  93  97  360  72.0
45  75  78  56  25  88  322  64.4
46  63  78  80  64  96  381  76.2
47  25  61  99  60  40  285  57.0
48  83  46  38  31  92  290  58.0
49  70  32  53  64  62  281  56.2
50  31  39  95  57  77  299  59.8

In [2]:
scores_df.sort_values(by='總分')

    國文  英文  數學  地理  歷史   總分    平均
13  45  31  32  22  39  169  33.8
32  62  26  60  43  33  224  44.8
28  33  40  22  36  97  228  45.6
36  29  54  29  29  87  228  45.6
35  62  22  33  32  82  231  46.2
19  22  25  72  36  77  232  46.4
8   44  48  23  66  57  238  47.6
3   54  30  23  74  67  248  49.6
20  33  81  25  67  57  263  52.6
12  53  38  79  33  60  263  52.6
2   32  84  40  24  85  265  53.0
38  58  49  27  58  79  271  54.2
34  31  70  94  29  52  276  55.2
17  47  48  31  73  78  277  55.4
18  45  69  83  36  44  277  55.4
6   25  37  48  88  80  278  55.6
49  70  32  53  64  62  281  56.2
26  92  25  70  46  49  282  56.4
30  41  74  21  72  75  283  56.6
47  25  61  99  60  40  285  57.0
41  43  45  36  84  81  289  57.8
23  35  95  60  42  57  289  57.8
48  83  46  38  31  92  290  58.0
16  20  66  59  75  76  296  59.2
14  85  94  46  31  43  299  59.8
50  31  39  95  57  77  299  59.8
31  43  70  60  62  65  300  60.0
5   89  64  80  30  37  300  60.0
27  26  44  58  85  91  304  60.8
1   77  47  80  78  32  314  62.8
33  86  90  38  25  77  316  63.2
22  92  31  84  46  64  317  63.4
9   51  64  73  45  84  317  63.4
45  75  78  56  25  88  322  64.4
37  84  51  22  70  99  326  65.2
43  71  64  61  97  34  327  65.4
39  24  56  88  62  98  328  65.6
21  22  76  83  81  75  337  67.4
11  41  97  79  36  88  341  68.2
24  45  87  34  81  96  343  68.6
7   62  87  91  31  81  352  70.4
15  76  44  83  72  78  353  70.6
40  70  61  91  55  81  358  71.6
44  57  71  42  93  97  360  72.0
10  65  92  42  78  85  362  72.4
42  84  73  69  95  41  362  72.4
29  96  88  33  49  98  364  72.8
4   49  95  98  85  39  366  73.2
25  98  72  52  85  60  367  73.4
46  63  78  80  64  96  381  76.2

In [3]:
#前五名
scores_df.sort_values(by='總分',ascending=False).iloc[:5]

    國文  英文  數學  地理  歷史   總分    平均
46  63  78  80  64  96  381  76.2
25  98  72  52  85  60  367  73.4
4   49  95  98  85  39  366  73.2
29  96  88  33  49  98  364  72.8
42  84  73  69  95  41  362  72.4

In [7]:
#後五名
scores_df.sort_values(by='總分',ascending=True).iloc[:5]

    國文  英文  數學  地理  歷史   總分    平均
13  45  31  32  22  39  169  33.8
32  62  26  60  43  33  224  44.8
28  33  40  22  36  97  228  45.6
36  29  54  29  29  87  228  45.6
35  62  22  33  32  82  231  46.2

In [12]:
#使用subscript[]，過濾資料
scores_df[scores_df['平均'] < 80]

    國文  英文  數學  地理  歷史   總分    平均
1   77  47  80  78  32  314  62.8
2   32  84  40  24  85  265  53.0
3   54  30  23  74  67  248  49.6
4   49  95  98  85  39  366  73.2
5   89  64  80  30  37  300  60.0
6   25  37  48  88  80  278  55.6
7   62  87  91  31  81  352  70.4
8   44  48  23  66  57  238  47.6
9   51  64  73  45  84  317  63.4
10  65  92  42  78  85  362  72.4
11  41  97  79  36  88  341  68.2
12  53  38  79  33  60  263  52.6
13  45  31  32  22  39  169  33.8
14  85  94  46  31  43  299  59.8
15  76  44  83  72  78  353  70.6
16  20  66  59  75  76  296  59.2
17  47  48  31  73  78  277  55.4
18  45  69  83  36  44  277  55.4
19  22  25  72  36  77  232  46.4
20  33  81  25  67  57  263  52.6
21  22  76  83  81  75  337  67.4
22  92  31  84  46  64  317  63.4
23  35  95  60  42  57  289  57.8
24  45  87  34  81  96  343  68.6
25  98  72  52  85  60  367  73.4
26  92  25  70  46  49  282  56.4
27  26  44  58  85  91  304  60.8
28  33  40  22  36  97  228  45.6
29  96  88  33  49  98  364  72.8
30  41  74  21  72  75  283  56.6
31  43  70  60  62  65  300  60.0
32  62  26  60  43  33  224  44.8
33  86  90  38  25  77  316  63.2
34  31  70  94  29  52  276  55.2
35  62  22  33  32  82  231  46.2
36  29  54  29  29  87  228  45.6
37  84  51  22  70  99  326  65.2
38  58  49  27  58  79  271  54.2
39  24  56  88  62  98  328  65.6
40  70  61  91  55  81  358  71.6
41  43  45  36  84  81  289  57.8
42  84  73  69  95  41  362  72.4
43  71  64  61  97  34  327  65.4
44  57  71  42  93  97  360  72.0
45  75  78  56  25  88  322  64.4
46  63  78  80  64  96  381  76.2
47  25  61  99  60  40  285  57.0
48  83  46  38  31  92  290  58.0
49  70  32  53  64  62  281  56.2
50  31  39  95  57  77  299  59.8

In [14]:
#平均80以下，歷史不及格的
scores_df[(scores_df['平均'] < 80) & (scores_df['歷史'] < 60)]

    國文  英文  數學  地理  歷史   總分    平均
1   77  47  80  78  32  314  62.8
4   49  95  98  85  39  366  73.2
5   89  64  80  30  37  300  60.0
8   44  48  23  66  57  238  47.6
13  45  31  32  22  39  169  33.8
14  85  94  46  31  43  299  59.8
18  45  69  83  36  44  277  55.4
20  33  81  25  67  57  263  52.6
23  35  95  60  42  57  289  57.8
26  92  25  70  46  49  282  56.4
32  62  26  60  43  33  224  44.8
34  31  70  94  29  52  276  55.2
42  84  73  69  95  41  362  72.4
43  71  64  61  97  34  327  65.4
47  25  61  99  60  40  285  57.0

In [15]:
#使用query()的搜尋
scores_df.query('平均<80 and 歷史<60')

    國文  英文  數學  地理  歷史   總分    平均
1   77  47  80  78  32  314  62.8
4   49  95  98  85  39  366  73.2
5   89  64  80  30  37  300  60.0
8   44  48  23  66  57  238  47.6
13  45  31  32  22  39  169  33.8
14  85  94  46  31  43  299  59.8
18  45  69  83  36  44  277  55.4
20  33  81  25  67  57  263  52.6
23  35  95  60  42  57  289  57.8
26  92  25  70  46  49  282  56.4
32  62  26  60  43  33  224  44.8
34  31  70  94  29  52  276  55.2
42  84  73  69  95  41  362  72.4
43  71  64  61  97  34  327  65.4
47  25  61  99  60  40  285  57.0